version: '2'
services:
    jhipgitrepo-app:
        image: jhipgitrepo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipgitrepo-postgresql:5432/jhipGitRepo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipgitrepo-postgresql:
        extends:
            file: postgresql.yml
            service: jhipgitrepo-postgresql
